import { useEffect, useState } from 'react'
import {
  Alert,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  ToastAndroid,
  TouchableOpacity,
  View,
} from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { router, useLocalSearchParams } from 'expo-router'
import * as Clipboard from 'expo-clipboard'
import * as FileSystem from 'expo-file-system'
import { getStatus, openFileNatively, ScanResults, UrlScanResult } from '../services/api'
import { ThreatScoreGauge } from '../components/ThreatScoreGauge'
import { VtConsensus } from '../components/VtConsensus'
import { IocList } from '../components/IocList'
import { GeoRisk } from '../components/GeoRisk'
import { COLORS, FONT } from '../constants/theme'

type Verdict = 'Malicious' | 'Suspicious' | 'Clear'

function getVerdictStyle(v: Verdict) {
  switch (v) {
    case 'Malicious':
      return {
        color: COLORS.verdicts.malicious,
        dim: COLORS.verdicts.maliciousDim,
        border: COLORS.verdicts.maliciousBorder,
        headline: 'HIGH CONFIDENCE THREAT DETECTED',
      }
    case 'Suspicious':
      return {
        color: COLORS.verdicts.suspicious,
        dim: COLORS.verdicts.suspiciousDim,
        border: COLORS.verdicts.suspiciousBorder,
        headline: 'SUSPICIOUS ACTIVITY DETECTED',
      }
    default:
      return {
        color: COLORS.verdicts.clear,
        dim: COLORS.verdicts.clearDim,
        border: COLORS.verdicts.clearBorder,
        headline: 'NO THREAT DETECTED',
      }
  }
}

async function copyToClipboard(value: string, label: string) {
  await Clipboard.setStringAsync(value)
  ToastAndroid.show(`${label} copied`, ToastAndroid.SHORT)
}

function UrlScanSection({ us }: { us: UrlScanResult }) {
  const hasData = us.is_malicious || us.verdict_score > 0 || us.page_title || us.page_ip || us.page_country
  if (!hasData) return null
  return (
    <View style={styles.card}>
      <View style={styles.cardHeaderRow}>
        <Text style={styles.sectionLabel}>URLSCAN.IO SANDBOX</Text>
        {us.is_malicious && (
          <View style={[styles.badge, { borderColor: COLORS.verdicts.maliciousBorder, backgroundColor: COLORS.verdicts.maliciousDim }]}>
            <Text style={[styles.badgeText, { color: COLORS.verdicts.malicious }]}>MALICIOUS</Text>
          </View>
        )}
        {!us.is_malicious && us.verdict_score > 0 && (
          <View style={[styles.badge, { borderColor: COLORS.verdicts.suspiciousBorder, backgroundColor: COLORS.verdicts.suspiciousDim }]}>
            <Text style={[styles.badgeText, { color: COLORS.verdicts.suspicious }]}>RISK {us.verdict_score}</Text>
          </View>
        )}
      </View>
      {us.page_title ? <Text style={styles.urlScanRow}>TITLE    {us.page_title}</Text> : null}
      {us.page_ip    ? <Text style={styles.urlScanRow}>PAGE IP  {us.page_ip}</Text> : null}
      {us.page_country ? <Text style={styles.urlScanRow}>COUNTRY  {us.page_country}</Text> : null}
    </View>
  )
}

export default function VerdictScreen() {
  const { jobId, originalUri, mimeType } = useLocalSearchParams<{
    jobId: string
    originalUri?: string
    mimeType?: string
  }>()

  const [results, setResults] = useState<ScanResults | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!jobId) return
    getStatus(jobId)
      .then(data => { if (data.results) setResults(data.results) })
      .catch(console.error)
      .finally(() => setLoading(false))
  }, [jobId])

  const handleShare = async (verdict: Verdict, r: ScanResults) => {
    const body = [
      '══ MALSCAN FORENSIC REPORT ══',
      '',
      `VERDICT     ${verdict.toUpperCase()}`,
      `SCORE       ${r.score}/100`,
      `FAMILY      ${r.family}`,
      `ATTRIBUTION ${r.attribution}`,
      '',
      '── THREAT INTELLIGENCE ──',
      ...(r.reasons.map(x => `• ${x}`)),
      '',
      '── TECHNICAL METADATA ──',
      `SHA-256  ${r.file_hash || 'N/A'}`,
      `IMPHASH  ${r.imphash || 'N/A'}`,
      `JOB ID   ${jobId}`,
      '',
      'Generated by MalScan Pro V.2.4',
    ].join('\n')

    try {
      await Share.share({ message: body, title: `MalScan: ${verdict}` })
    } catch {
      // User cancelled share — no action needed
    }
  }

  const handleContinueToOpen = async () => {
    if (!originalUri) {
      Alert.alert('No file', 'Original file URI not available for pass-through.')
      return
    }
    try {
      await openFileNatively(originalUri, mimeType || undefined)
      const cached = `${FileSystem.cacheDirectory}malscan_upload`
      await FileSystem.deleteAsync(cached, { idempotent: true })
    } catch {
      Alert.alert('Cannot open', 'No app found to handle this file type.')
    }
  }

  const handleBlockAndDelete = () => {
    Alert.alert(
      'Block & Delete',
      'This will discard the file from MalScan memory. The original in the sending app is unaffected.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Confirm Block',
          style: 'destructive',
          onPress: async () => {
            if (originalUri) await FileSystem.deleteAsync(originalUri, { idempotent: true })
            router.replace('/')
          },
        },
      ],
    )
  }

  // ── Loading / error states ──────────────────────────────────────────────────

  if (loading) {
    return (
      <SafeAreaView style={styles.safe}>
        <View style={styles.centred}>
          <Text style={styles.loadingText}>LOADING RESULTS...</Text>
        </View>
      </SafeAreaView>
    )
  }

  if (!results) {
    return (
      <SafeAreaView style={styles.safe}>
        <View style={styles.centred}>
          <Text style={styles.errorText}>FAILED TO LOAD RESULTS</Text>
          <TouchableOpacity style={styles.homeBtn} onPress={() => router.replace('/')}>
            <Text style={styles.homeBtnText}>← BACK TO HOME</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    )
  }

  // ── Main render ────────────────────────────────────────────────────────────

  const verdict = results.verdict as Verdict
  const vs = getVerdictStyle(verdict)
  const vtStats = results.osint_summary?.virustotal
  const urlScan = results.osint_summary?.urlscan
  const osint = results.osint_summary
  const apkInfo = results.apk_info
  const archiveContents = results.archive_contents || []
  const isClear = verdict === 'Clear'

  return (
    <SafeAreaView style={styles.safe}>
      {/* ── Header bar ─────────────────────────────────────────────────────── */}
      <View style={[styles.headerBar, { borderBottomColor: vs.border, backgroundColor: vs.dim }]}>
        <View>
          <Text style={styles.headerEyebrow}>ANALYSIS COMPLETE</Text>
          <Text style={[styles.verdictLabel, { color: vs.color }]}>{verdict.toUpperCase()}</Text>
        </View>
        <View style={styles.headerActions}>
          <TouchableOpacity
            style={styles.iconBtn}
            onPress={() => handleShare(verdict, results)}
          >
            <Text style={styles.iconBtnText}>⬆ SHARE</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.homeBtn} onPress={() => router.replace('/')}>
            <Text style={styles.homeBtnText}>HOME</Text>
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent}>

        {/* ── Score + headline ───────────────────────────────────────────── */}
        <View style={[styles.card, { borderColor: vs.border, backgroundColor: vs.dim }]}>
          <ThreatScoreGauge score={results.score} color={vs.color} />
          <Text style={[styles.headline, { color: vs.color }]}>{vs.headline}</Text>
          <View style={styles.metaRow}>
            <View style={styles.metaItem}>
              <Text style={styles.metaLabel}>FAMILY</Text>
              <Text style={styles.metaValue}>{results.family}</Text>
            </View>
            <View style={styles.metaItem}>
              <Text style={styles.metaLabel}>ATTRIBUTION</Text>
              <Text style={styles.metaValue}>{results.attribution}</Text>
            </View>
          </View>
        </View>

        {/* ── Threat intelligence reasons ────────────────────────────────── */}
        {results.reasons.length > 0 && (
          <View style={styles.card}>
            <Text style={styles.sectionLabel}>THREAT INTELLIGENCE SUMMARY</Text>
            {results.reasons.map((r, i) => (
              <View key={i} style={styles.reasonRow}>
                <Text style={[styles.reasonBullet, { color: vs.color }]}>▸</Text>
                <Text style={styles.reasonText}>{r}</Text>
              </View>
            ))}
          </View>
        )}

        {/* ── VirusTotal consensus ────────────────────────────────────────── */}
        {vtStats && <VtConsensus stats={vtStats} />}

        {/* ── URLScan.io sandbox ──────────────────────────────────────────── */}
        {urlScan && <UrlScanSection us={urlScan} />}

        {/* ── Infrastructure intelligence ─────────────────────────────────── */}
        {(osint?.country || osint?.asn || osint?.registrar) && (
          <GeoRisk osint={osint} />
        )}

        {/* ── APK Permissions ─────────────────────────────────────────────── */}
        {apkInfo?.is_apk && (
          <View style={styles.card}>
            <View style={styles.cardHeaderRow}>
              <Text style={styles.sectionLabel}>ANDROID APK ANALYSIS</Text>
              {(apkInfo.dangerous_permissions?.length ?? 0) > 0 && (
                <View style={[styles.badge, { borderColor: COLORS.verdicts.suspiciousBorder, backgroundColor: COLORS.verdicts.suspiciousDim }]}>
                  <Text style={[styles.badgeText, { color: COLORS.verdicts.suspicious }]}>
                    {apkInfo.dangerous_permissions.length} DANGEROUS
                  </Text>
                </View>
              )}
            </View>
            {apkInfo.package    ? <Text style={styles.apkMeta}>PACKAGE: {apkInfo.package}</Text> : null}
            {apkInfo.app_label  ? <Text style={styles.apkMeta}>APP: {apkInfo.app_label}</Text> : null}
            {(apkInfo.dangerous_permissions?.length ?? 0) > 0 && (
              <View style={styles.permGrid}>
                {apkInfo.dangerous_permissions.map(p => (
                  <View key={p} style={styles.permChip}>
                    <Text style={styles.permText}>{p.replace('android.permission.', '')}</Text>
                  </View>
                ))}
              </View>
            )}
          </View>
        )}

        {/* ── Archive contents ─────────────────────────────────────────────── */}
        {archiveContents.length > 0 && (
          <View style={styles.card}>
            <Text style={styles.sectionLabel}>ARCHIVE CONTENTS ({archiveContents.length} FILES)</Text>
            {archiveContents.map((f, i) => (
              <View key={i} style={styles.archiveRow}>
                <Text style={styles.archiveName} numberOfLines={1}>{f.name}</Text>
                <View style={styles.archiveTags}>
                  {f.is_pe && <Text style={styles.archiveTagPe}>PE</Text>}
                  {f.ioc_count > 0 && <Text style={styles.archiveTagIoc}>{f.ioc_count} IOCs</Text>}
                </View>
              </View>
            ))}
          </View>
        )}

        {/* ── IOC terminal ─────────────────────────────────────────────────── */}
        <IocList indicators={results.indicators} />

        {/* ── Technical footer — long-press any row to copy ────────────────── */}
        <View style={styles.techFooter}>
          {[
            { label: 'SHA-256', value: results.file_hash || 'N/A' },
            { label: 'IMPHASH', value: results.imphash || 'Not a PE file' },
            { label: 'JOB ID',  value: jobId || 'N/A' },
          ].map(({ label, value }) => (
            <TouchableOpacity
              key={label}
              style={styles.techRow}
              onLongPress={() => copyToClipboard(value, label)}
              activeOpacity={0.7}
            >
              <Text style={styles.techLabel}>{label}</Text>
              <Text style={styles.techValue} numberOfLines={1}>{value}</Text>
              <Text style={styles.techCopy}>⧉</Text>
            </TouchableOpacity>
          ))}
          <Text style={styles.techHint}>Long-press any row to copy</Text>
        </View>

        {/* ── Action buttons ───────────────────────────────────────────────── */}
        <View style={styles.actions}>
          {isClear && originalUri ? (
            <TouchableOpacity
              style={[styles.actionBtn, styles.actionBtnClear]}
              onPress={handleContinueToOpen}
              activeOpacity={0.85}
            >
              <Text style={styles.actionBtnText}>CONTINUE TO OPEN →</Text>
            </TouchableOpacity>
          ) : null}

          <TouchableOpacity
            style={[styles.actionBtn, isClear ? styles.actionBtnSecondary : styles.actionBtnBlock]}
            onPress={isClear ? () => router.replace('/') : handleBlockAndDelete}
            activeOpacity={0.85}
          >
            <Text style={[styles.actionBtnText, isClear && styles.actionBtnTextSecondary]}>
              {isClear ? 'DONE' : 'BLOCK & DELETE FILE'}
            </Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  centred: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 20 },
  loadingText: {
    fontFamily: FONT.mono,
    fontSize: 12,
    color: COLORS.text.secondary,
    letterSpacing: 3,
  },
  errorText: {
    fontFamily: FONT.mono,
    fontSize: 12,
    color: COLORS.verdicts.malicious,
    letterSpacing: 3,
  },

  // Header bar
  headerBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  headerEyebrow: {
    fontFamily: FONT.mono,
    fontSize: 8,
    color: COLORS.text.muted,
    letterSpacing: 3,
    marginBottom: 2,
  },
  verdictLabel: {
    fontFamily: FONT.mono,
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 4,
  },
  headerActions: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  iconBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  iconBtnText: {
    fontFamily: FONT.mono,
    fontSize: 9,
    color: COLORS.text.secondary,
    letterSpacing: 2,
  },
  homeBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  homeBtnText: {
    fontFamily: FONT.mono,
    fontSize: 10,
    color: COLORS.text.secondary,
    letterSpacing: 2,
  },

  scroll: { flex: 1 },
  scrollContent: { padding: 16, gap: 12, paddingBottom: 40 },

  // Cards
  card: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    padding: 16,
    gap: 10,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionLabel: {
    fontFamily: FONT.mono,
    fontSize: 9,
    color: COLORS.text.secondary,
    letterSpacing: 3,
  },

  // Score card
  headline: {
    fontFamily: FONT.mono,
    fontSize: 13,
    fontWeight: 'bold',
    letterSpacing: 2,
    textAlign: 'center',
  },
  metaRow: { flexDirection: 'row', justifyContent: 'space-around' },
  metaItem: { alignItems: 'center' },
  metaLabel: {
    fontFamily: FONT.mono,
    fontSize: 8,
    color: COLORS.text.muted,
    letterSpacing: 2,
    marginBottom: 4,
  },
  metaValue: { fontFamily: FONT.mono, fontSize: 11, color: COLORS.text.primary, letterSpacing: 1 },

  // Reasons
  reasonRow: { flexDirection: 'row', gap: 8 },
  reasonBullet: { fontFamily: FONT.mono, fontSize: 12, lineHeight: 18 },
  reasonText: {
    fontFamily: FONT.mono,
    fontSize: 11,
    color: COLORS.text.secondary,
    flex: 1,
    lineHeight: 17,
    letterSpacing: 0.3,
  },

  // URLScan
  urlScanRow: {
    fontFamily: FONT.mono,
    fontSize: 10,
    color: COLORS.text.secondary,
    letterSpacing: 0.5,
    lineHeight: 16,
  },

  // Badge (shared)
  badge: {
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeText: {
    fontFamily: FONT.mono,
    fontSize: 8,
    letterSpacing: 1,
  },

  // APK
  apkMeta: { fontFamily: FONT.mono, fontSize: 10, color: COLORS.text.secondary, letterSpacing: 0.5 },
  permGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  permChip: {
    borderWidth: 1,
    borderColor: '#3B0000',
    backgroundColor: '#1A0000',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  permText: { fontFamily: FONT.mono, fontSize: 9, color: '#EF4444', letterSpacing: 0.5 },

  // Archive
  archiveRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderFaint,
  },
  archiveName: { fontFamily: FONT.mono, fontSize: 10, color: COLORS.text.secondary, flex: 1 },
  archiveTags: { flexDirection: 'row', gap: 6 },
  archiveTagPe: {
    fontFamily: FONT.mono,
    fontSize: 8,
    color: COLORS.verdicts.suspicious,
    borderWidth: 1,
    borderColor: COLORS.verdicts.suspiciousBorder,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  archiveTagIoc: { fontFamily: FONT.mono, fontSize: 8, color: COLORS.accent, letterSpacing: 0.5 },

  // Tech footer
  techFooter: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  techRow: {
    flexDirection: 'row',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderFaint,
    gap: 10,
    alignItems: 'center',
  },
  techLabel: {
    fontFamily: FONT.mono,
    fontSize: 9,
    color: COLORS.text.muted,
    letterSpacing: 2,
    width: 72,
  },
  techValue: { fontFamily: FONT.mono, fontSize: 10, color: COLORS.text.secondary, flex: 1 },
  techCopy: { fontSize: 12, color: COLORS.text.muted },
  techHint: {
    fontFamily: FONT.mono,
    fontSize: 8,
    color: COLORS.text.muted,
    letterSpacing: 1,
    textAlign: 'center',
    paddingVertical: 8,
  },

  // Actions
  actions: { gap: 10, marginTop: 4 },
  actionBtn: { paddingVertical: 16, alignItems: 'center', borderWidth: 1 },
  actionBtnClear: { backgroundColor: COLORS.verdicts.clear, borderColor: COLORS.verdicts.clear },
  actionBtnBlock: { backgroundColor: COLORS.verdicts.maliciousDim, borderColor: COLORS.verdicts.maliciousBorder },
  actionBtnSecondary: { backgroundColor: 'transparent', borderColor: COLORS.border },
  actionBtnText: {
    fontFamily: FONT.mono,
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
    letterSpacing: 3,
  },
  actionBtnTextSecondary: { color: COLORS.text.secondary },
})
