import { useState, useEffect, useRef } from 'react'
import {
  Alert, Animated, ScrollView, Share, StyleSheet, Text,
  ToastAndroid, TouchableOpacity, Vibration, View,
} from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { router, useLocalSearchParams } from 'expo-router'
import * as Clipboard from 'expo-clipboard'
import * as FileSystem from 'expo-file-system'
import { getStatus, openFileNatively, ScanResults, UrlScanResult } from '../services/api'
import { ThreatScoreGauge } from '../components/ThreatScoreGauge'
import { VtConsensus } from '../components/VtConsensus'
import { IocList } from '../components/IocList'
import { GeoRisk } from '../components/GeoRisk'
import { PressableScale } from '../components/PressableScale'
import { useTheme } from '../contexts/ThemeContext'

type Verdict = 'Malicious' | 'Suspicious' | 'Clear'

function getVerdictDisplay(v: Verdict, colors: any) {
  switch (v) {
    case 'Malicious': return {
      emoji: '⛔',
      label: 'Do Not Open',
      sublabel: 'This file is dangerous. Delete it immediately.',
      color: colors.verdicts.malicious,
      dim: colors.verdicts.maliciousDim,
      border: colors.verdicts.maliciousBorder,
    }
    case 'Suspicious': return {
      emoji: '⚠️',
      label: 'Proceed with Caution',
      sublabel: 'Something unusual was detected. Verify before opening.',
      color: colors.verdicts.suspicious,
      dim: colors.verdicts.suspiciousDim,
      border: colors.verdicts.suspiciousBorder,
    }
    default: return {
      emoji: '✅',
      label: 'Safe to Open',
      sublabel: 'No threats were found in this file.',
      color: colors.verdicts.clear,
      dim: colors.verdicts.clearDim,
      border: colors.verdicts.clearBorder,
    }
  }
}

async function copyValue(value: string, label: string) {
  await Clipboard.setStringAsync(value)
  ToastAndroid.show(`${label} copied`, ToastAndroid.SHORT)
}

function Section({ title, children, defaultOpen = false }: { title: string; children: React.ReactNode; defaultOpen?: boolean }) {
  const [open, setOpen] = useState(defaultOpen)
  const { colors, fonts } = useTheme()
  return (
    <View style={{ marginBottom: 10 }}>
      <TouchableOpacity
        style={{
          flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
          backgroundColor: colors.surface, borderRadius: 12, padding: 16,
          borderWidth: 1, borderColor: colors.border,
        }}
        onPress={() => setOpen(o => !o)}
        activeOpacity={0.75}
      >
        <Text style={{ fontFamily: fonts.heading, fontSize: 14, fontWeight: '600', color: colors.text.primary }}>
          {title}
        </Text>
        <Text style={{ fontFamily: fonts.body, fontSize: 18, color: colors.text.muted }}>{open ? '−' : '+'}</Text>
      </TouchableOpacity>
      {open && (
        <View style={{ backgroundColor: colors.surface, borderRadius: 12, marginTop: 2, borderWidth: 1, borderColor: colors.border, padding: 16 }}>
          {children}
        </View>
      )}
    </View>
  )
}

export default function VerdictScreen() {
  const { colors, fonts } = useTheme()
  const { jobId, originalUri, mimeType } = useLocalSearchParams<{
    jobId: string; originalUri?: string; mimeType?: string
  }>()

  const [results, setResults] = useState<ScanResults | null>(null)
  const [loading, setLoading] = useState(true)

  const s = makeStyles(colors, fonts)

  useEffect(() => {
    if (!jobId) return
    getStatus(jobId)
      .then(d => { if (d.results) setResults(d.results) })
      .catch(console.error)
      .finally(() => setLoading(false))
  }, [jobId])

  // Verdict reveal: entrance animation + a vibration pattern matching severity
  const heroAnim = useRef(new Animated.Value(0)).current
  useEffect(() => {
    if (!results) return
    Animated.spring(heroAnim, { toValue: 1, useNativeDriver: true, speed: 14, bounciness: 7 }).start()
    if (results.verdict === 'Malicious')        Vibration.vibrate([0, 90, 70, 90, 70, 180])
    else if (results.verdict === 'Suspicious')  Vibration.vibrate([0, 70, 90, 70])
    else                                        Vibration.vibrate(35)
  }, [results]) // eslint-disable-line react-hooks/exhaustive-deps

  const handleShare = async (v: Verdict, r: ScanResults) => {
    const body = [
      'MalScan Security Report',
      '========================',
      `Verdict:     ${v === 'Clear' ? 'Safe to Open' : v === 'Suspicious' ? 'Proceed with Caution' : 'Do Not Open'}`,
      `Risk Score:  ${r.score}/100`,
      `Family:      ${r.family}`,
      '',
      r.reasons.length > 0 ? 'Findings:\n' + r.reasons.map(x => `• ${x}`).join('\n') : 'No threats detected.',
      '',
      `SHA-256: ${r.file_hash || 'N/A'}`,
      `Job ID:  ${jobId}`,
      '',
      'Generated by MalScan',
    ].join('\n')
    try { await Share.share({ message: body }) } catch {}
  }

  const handleOpen = async () => {
    if (!originalUri) { Alert.alert('No file', 'Original file not available.'); return }
    try {
      await openFileNatively(originalUri, mimeType || undefined)
      await FileSystem.deleteAsync(`${FileSystem.cacheDirectory}malscan_upload`, { idempotent: true })
    } catch { Alert.alert('Cannot open', 'No app found to handle this file type.') }
  }

  const handleOpenAnyway = () => {
    Alert.alert(
      'Open this file anyway?',
      'MalScan flagged this file as suspicious. Opening it could put your device at risk. Only continue if you trust where it came from.',
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Open Anyway', style: 'destructive', onPress: handleOpen },
      ],
    )
  }

  const handleDelete = () => {
    Alert.alert(
      'Discard File',
      "This removes MalScan's working copy so the file can't be opened from here. The original still exists in the app it came from (e.g. WhatsApp) — delete it there too.",
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Discard', style: 'destructive', onPress: async () => {
          try {
            if (originalUri) await FileSystem.deleteAsync(originalUri, { idempotent: true })
            ToastAndroid.show('Working copy removed', ToastAndroid.SHORT)
          } catch {
            ToastAndroid.show('Copy already removed', ToastAndroid.SHORT)
          }
          router.replace('/')
        }},
      ],
    )
  }

  if (loading) {
    return (
      <SafeAreaView style={s.safe}>
        <View style={s.centred}><Text style={s.loadingText}>Loading results...</Text></View>
      </SafeAreaView>
    )
  }

  if (!results) {
    return (
      <SafeAreaView style={s.safe}>
        <View style={s.centred}>
          <Text style={s.errorText}>Could not load results</Text>
          <TouchableOpacity style={s.retryBtn} onPress={() => router.replace('/')}>
            <Text style={s.retryBtnText}>Go Home</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    )
  }

  const verdict = results.verdict as Verdict
  const vd = getVerdictDisplay(verdict, colors)
  const isClear = verdict === 'Clear'
  const vtStats = results.osint_summary?.virustotal
  const urlScan = results.osint_summary?.urlscan
  const osint = results.osint_summary
  const apkInfo = results.apk_info
  const archiveContents = results.archive_contents || []
  const hasUrlScanData = urlScan && (urlScan.is_malicious || urlScan.verdict_score > 0 || urlScan.page_title || urlScan.page_ip)

  return (
    <SafeAreaView style={s.safe}>
      {/* Header */}
      <View style={s.topBar}>
        <TouchableOpacity style={s.topBtn} onPress={() => router.replace('/')}>
          <Text style={s.topBtnText}>← Home</Text>
        </TouchableOpacity>
        <TouchableOpacity style={s.topBtn} onPress={() => handleShare(verdict, results)}>
          <Text style={s.topBtnText}>Share Report</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={s.scroll}>

        {/* ── Verdict hero ───────────────────────────────────────────────── */}
        <Animated.View
          style={[
            s.verdictCard,
            { backgroundColor: vd.dim, borderColor: vd.border },
            {
              opacity: heroAnim,
              transform: [{ scale: heroAnim.interpolate({ inputRange: [0, 1], outputRange: [0.92, 1] }) }],
            },
          ]}
        >
          <Text style={s.verdictEmoji}>{vd.emoji}</Text>
          <Text style={[s.verdictLabel, { color: vd.color }]}>{vd.label}</Text>
          <Text style={s.verdictSublabel}>{vd.sublabel}</Text>
          <ThreatScoreGauge score={results.score} color={vd.color} />
        </Animated.View>

        {/* ── Action buttons ─────────────────────────────────────────────── */}
        <View style={s.actions}>
          {isClear && originalUri && (
            <PressableScale style={[s.actionBtn, { backgroundColor: colors.verdicts.clear }]} onPress={handleOpen}>
              <Text style={s.actionBtnText}>Open File</Text>
            </PressableScale>
          )}
          {!isClear && (
            <PressableScale
              style={[s.actionBtn, { backgroundColor: colors.verdicts.maliciousDim, borderWidth: 1, borderColor: colors.verdicts.maliciousBorder }]}
              onPress={handleDelete}
            >
              <Text style={[s.actionBtnText, { color: colors.verdicts.malicious }]}>Discard File</Text>
            </PressableScale>
          )}
          {verdict === 'Suspicious' && originalUri && (
            <PressableScale
              style={[s.actionBtn, { backgroundColor: colors.verdicts.suspiciousDim, borderWidth: 1, borderColor: colors.verdicts.suspiciousBorder }]}
              onPress={handleOpenAnyway}
            >
              <Text style={[s.actionBtnText, { color: colors.verdicts.suspicious }]}>Open Anyway</Text>
            </PressableScale>
          )}
          <PressableScale
            style={[s.actionBtn, { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }]}
            onPress={() => router.replace('/')}
          >
            <Text style={[s.actionBtnText, { color: colors.text.secondary }]}>Done</Text>
          </PressableScale>
        </View>

        {/* ── Key findings ───────────────────────────────────────────────── */}
        {results.reasons.length > 0 && (
          <Section title={`What we found (${results.reasons.length})`} defaultOpen>
            {results.reasons.map((r, i) => (
              <View key={i} style={s.reasonRow}>
                <Text style={[s.reasonBullet, { color: vd.color }]}>•</Text>
                <Text style={s.reasonText}>{r}</Text>
              </View>
            ))}
          </Section>
        )}

        {/* ── VirusTotal ─────────────────────────────────────────────────── */}
        {vtStats && (
          <Section title="Security engine results" defaultOpen>
            <VtConsensus stats={vtStats} />
          </Section>
        )}

        {/* ── URLScan ────────────────────────────────────────────────────── */}
        {hasUrlScanData && (
          <Section title="Sandbox analysis">
            <View style={s.urlScanRows}>
              {urlScan!.page_title   && <Text style={s.urlScanRow}>Page title:  {urlScan!.page_title}</Text>}
              {urlScan!.page_ip      && <Text style={s.urlScanRow}>Server IP:   {urlScan!.page_ip}</Text>}
              {urlScan!.page_country && <Text style={s.urlScanRow}>Country:     {urlScan!.page_country}</Text>}
              {urlScan!.is_malicious && <Text style={[s.urlScanRow, { color: colors.verdicts.malicious, fontWeight: '600' }]}>⛔ Flagged as malicious by URLScan</Text>}
            </View>
          </Section>
        )}

        {/* ── Infrastructure ─────────────────────────────────────────────── */}
        {(osint?.country || osint?.asn || osint?.registrar) && (
          <Section title="Server & network details">
            <GeoRisk osint={osint} />
          </Section>
        )}

        {/* ── APK permissions ────────────────────────────────────────────── */}
        {apkInfo?.is_apk && (
          <Section title={`Android permissions${(apkInfo.dangerous_permissions?.length ?? 0) > 0 ? ` · ${apkInfo.dangerous_permissions.length} dangerous` : ''}`}>
            {apkInfo.package    && <Text style={s.apkRow}>Package: {apkInfo.package}</Text>}
            {apkInfo.app_label  && <Text style={s.apkRow}>App name: {apkInfo.app_label}</Text>}
            {(apkInfo.dangerous_permissions || []).map(p => (
              <View key={p} style={s.permChip}>
                <Text style={s.permText}>{p.replace('android.permission.', '')}</Text>
              </View>
            ))}
          </Section>
        )}

        {/* ── Archive contents ────────────────────────────────────────────── */}
        {archiveContents.length > 0 && (
          <Section title={`Archive contents (${archiveContents.length} files)`}>
            {archiveContents.map((f, i) => (
              <View key={i} style={s.archiveRow}>
                <Text style={s.archiveName} numberOfLines={1}>{f.name}</Text>
                {f.is_pe && <Text style={[s.archiveTag, { color: colors.verdicts.suspicious }]}>EXE</Text>}
                {f.ioc_count > 0 && <Text style={[s.archiveTag, { color: colors.text.muted }]}>{f.ioc_count} links</Text>}
              </View>
            ))}
          </Section>
        )}

        {/* ── IOCs ───────────────────────────────────────────────────────── */}
        <Section title="Extracted network indicators">
          <IocList indicators={results.indicators} />
        </Section>

        {/* ── Technical metadata ─────────────────────────────────────────── */}
        <Section title="Technical details">
          {[
            { label: 'SHA-256', value: results.file_hash || 'N/A' },
            { label: 'Imphash', value: results.imphash || 'Not a Windows executable' },
            { label: 'Family',  value: results.family },
            { label: 'Attributed to', value: results.attribution },
            { label: 'Job ID',  value: jobId || 'N/A' },
          ].map(({ label, value }) => (
            <TouchableOpacity key={label} style={s.techRow} onLongPress={() => copyValue(value, label)} activeOpacity={0.7}>
              <Text style={s.techLabel}>{label}</Text>
              <Text style={s.techValue} numberOfLines={1}>{value}</Text>
            </TouchableOpacity>
          ))}
          <Text style={s.techHint}>Long-press any row to copy</Text>
        </Section>

      </ScrollView>
    </SafeAreaView>
  )
}

const makeStyles = (colors: any, fonts: any) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  centred: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 20 },
  loadingText: { fontFamily: fonts.body, fontSize: 15, color: colors.text.secondary },
  errorText: { fontFamily: fonts.heading, fontSize: 16, color: colors.verdicts.malicious },
  retryBtn: { backgroundColor: colors.surface, borderRadius: 12, paddingHorizontal: 24, paddingVertical: 12 },
  retryBtnText: { fontFamily: fonts.body, fontSize: 14, color: colors.text.secondary },

  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.border },
  topBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  topBtnText: { fontFamily: fonts.body, fontSize: 13, color: colors.text.secondary },

  scroll: { padding: 20, gap: 10, paddingBottom: 48 },

  verdictCard: { borderRadius: 22, paddingVertical: 32, paddingHorizontal: 24, alignItems: 'center', borderWidth: 1, marginBottom: 4, gap: 12 },
  verdictEmoji: { fontSize: 40, marginBottom: 2 },
  verdictLabel: { fontFamily: fonts.heading, fontSize: 27, fontWeight: '700', textAlign: 'center', letterSpacing: 0.3 },
  verdictSublabel: { fontFamily: fonts.body, fontSize: 14, color: colors.text.secondary, textAlign: 'center', lineHeight: 21, maxWidth: 300 },

  actions: { gap: 10, marginBottom: 4 },
  actionBtn: { borderRadius: 14, paddingVertical: 16, alignItems: 'center' },
  actionBtnText: { fontFamily: fonts.heading, fontSize: 15, fontWeight: '600', color: '#fff' },

  reasonRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  reasonBullet: { fontSize: 14, lineHeight: 20 },
  reasonText: { fontFamily: fonts.body, fontSize: 13, color: colors.text.secondary, flex: 1, lineHeight: 20 },

  urlScanRows: { gap: 6 },
  urlScanRow: { fontFamily: fonts.body, fontSize: 13, color: colors.text.secondary, lineHeight: 20 },

  apkRow: { fontFamily: fonts.body, fontSize: 13, color: colors.text.secondary, marginBottom: 6 },
  permChip: { backgroundColor: colors.verdicts.maliciousDim, borderRadius: 6, paddingHorizontal: 10, paddingVertical: 5, marginBottom: 5, alignSelf: 'flex-start' },
  permText: { fontFamily: fonts.mono, fontSize: 11, color: colors.verdicts.malicious },

  archiveRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: colors.borderFaint, gap: 10 },
  archiveName: { fontFamily: fonts.body, fontSize: 13, color: colors.text.secondary, flex: 1 },
  archiveTag: { fontFamily: fonts.body, fontSize: 11 },

  techRow: { flexDirection: 'row', gap: 12, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.borderFaint },
  techLabel: { fontFamily: fonts.body, fontSize: 12, color: colors.text.muted, width: 100 },
  techValue: { fontFamily: fonts.mono, fontSize: 11, color: colors.text.secondary, flex: 1 },
  techHint: { fontFamily: fonts.body, fontSize: 11, color: colors.text.muted, textAlign: 'center', marginTop: 10 },
})
